GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6667fe8256792068808991d8

###
DELETE http://localhost:3001/api/notes/6667fe8256792068808991d8

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Hello FSO Part 4",
    "important": true
}
