GET http://localhost:3001/api/contacts

###
GET http://localhost:3001/api/contacts/66668f776b3b6a019e65622b

### 
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/contacts/66668fcd6b3b6a019e65623a

###
POST http://localhost:3001/api/contacts
Content-Type: application/json 

{
    "number": "114514"
}

###
POST http://localhost:3001/api/contacts
Content-Type: application/json 

{
    "name": "harry potter"
}

###
POST http://localhost:3001/api/contacts
Content-Type: application/json 

{
    "name": "Arto Hellas",
    "number": "114514"
}

###
POST http://localhost:3001/api/contacts
Content-Type: application/json 

{
    "name": "Harry Potter",
    "number": "114514"
}

### 
HEAD http://localhost:3001/api/contacts
