GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6667fe8256792068808991d8

###
DELETE http://localhost:3001/api/notes/666aee0fdc222b876f3300dc

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2NzJlZmY1ODhlNjMzYzVhNDA4N2MwYSIsImlhdCI6MTcxODgxMDU1NywiZXhwIjoxNzE4ODE0MTU3fQ.Hc7YczV6ACLEhk_65zdg1me6C9fruDPwJhcnBO5v7bA

{
    "content": "Use token",
    "important": true,
    "userId": "6672eff588e633c5a4087c0a"
}

###
PUT http://localhost:3001/api/notes/6672f7c977a5422e4b2cac8e
Content-Type: application/json

{
    "content": "Use token",
    "important": true,
    "userId": "6672eff588e633c5a4087c0a"
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

### 
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}